#!/usr/bin/python3

import os, sys

def run():
    if not os.path.isfile(f"build/bin/gol"):
        raise("gol haven't compiled")
    
    os.system("./build/bin/gol")

def make():
    source_files = [
        "control.cc",
        "main.cc",
        "rendering.cc",
        "cell.cc"
    ]

    header_files = [
        "control.hh",
        "rendering.hh",
        "cell.hh",
        "rendering.hh",
        "types.hh"
    ]

    # --- Check if Files Exist ---
    for i in header_files:
        if not os.path.isfile(f"src/{i}"):
            raise(f"src/{i} expected to exist but it's not")

    for i in source_files:
        if not os.path.isfile(f"src/{i}"):
            raise(f"src/{i} expected to exist but it's not")

    # --- Compiling Source Files ---
    # - Preparing Build Folder
    try:
        os.system("rm -rf build/")
        os.mkdir("build/")
        os.mkdir("build/obj")
        os.mkdir("build/bin")
    except: pass

    # --- Compile Source
    for i in source_files:
        print(f"Compiling {i}...")
        os.system(f"g++ -c src/{i} -o build/obj/{i.replace('.cc', '.obj')}")

    # --- Linking
    links = "".join(
        [
            f"build/obj/{i.replace('.cc', '.obj')} "
            for i in source_files
        ]
    )

    os.system(f"g++ {links} -o build/bin/gol -lGL -lGLU -lglut")

if __name__ == "__main__":
    try: arg = sys.argv[1]
    except: raise("Arguments not Provided !")

    if arg.lower() == "compile":
        make()
    elif arg.lower() == "run":
        run()
    else:
        raise("Argument not supported!")
    